M48
; DRILL file {KiCad 7.0.6} date Mon Jul 24 19:35:12 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-24T19:35:12+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X7.9Y-1.3
T2
X2.9Y-1.3
X2.9Y-4.9
X7.9Y-4.9
T0
M30
