M48
; DRILL file {KiCad 7.0.6} date Mon Jul 24 14:10:13 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-24T14:10:13+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X6.0Y-3.3
X6.0Y-3.9
T2
X5.4Y-3.3
X5.5Y-3.3
T3
X5.4Y-3.8
X5.4Y-3.9
T0
M30
